#!/usr/bin/env python3
"""
tools/osm-world/ci/chunk-shards.py — turn shards.json into a GitHub Actions matrix.

See PLAN.md §Phase 4. Consumed by .github/workflows/world-density-shards.yml and
world-feature-shards.yml, both of which need a dynamic matrix (the shard count is
decided by cover.py's Geofabrik-derived cover, not known when the workflow is
authored) that stays under the platform's 256-entry-per-matrix cap.

shards.json (the pinned interface written by cover.py) has the shape:

    {
      "generated_from": "geofabrik index-v1.json <date>",
      "coarse": [{"id": "...", "pbf_url": "...", "md5_url": "...", "est_bytes": N}],
      "fine":   [{..same.., "disjoint_neighbors": ["..."]}]
    }

This script reads one of those two arrays, groups it into fixed-size batches (a
GitHub matrix *job* runs one batch, looping over its shards sequentially — that is
what keeps 499 fine shards under 256 jobs without raising per-job concurrency), and
prints a JSON array of `{"batch_id", "shards"}` objects suitable for:

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}

`disjoint_neighbors` (fine-only) is not consumed here, and it is not a merge input
either: the density exactness rule is enforced at BUILD time (build-shard.sh passes
cover.py's cover-geometries/<id>.geojson — the shard's assigned disjoint polygon —
to `build.py --clip-region`; merge.py just sums cells). `disjoint_neighbors` records
which fine shards can share a boundary density cell — diagnostic/bookkeeping data,
not a scheduling input for CI.

No third-party dependencies (stdlib json/argparse only) so a bare `python3` on the
runner can run it without an `uv` setup step.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def chunk(items: list, size: int) -> list[list]:
    if size < 1:
        raise ValueError("batch size must be >= 1")
    return [items[i:i + size] for i in range(0, len(items), size)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shards-json", type=Path,
                        default=Path(__file__).resolve().parent.parent / "shards.json",
                        help="path to shards.json (default: tools/osm-world/shards.json)")
    parser.add_argument("--kind", required=True, choices=["coarse", "fine"],
                        help="which array of shards.json to batch")
    parser.add_argument("--batch-size", type=int, required=True,
                        help="shards per matrix job (one job loops over its batch "
                             "sequentially inside build-shard.sh)")
    parser.add_argument("--max-jobs", type=int, default=256,
                        help="hard cap on emitted matrix entries (GitHub Actions "
                             "limit; default 256)")
    parser.add_argument("--id-prefix", default=None,
                        help="batch_id prefix (default: --kind)")
    args = parser.parse_args(argv)

    if not args.shards_json.exists():
        print(
            f"error: {args.shards_json} not found.\n"
            "shards.json is generated by cover.py (see PLAN.md §Phase 3/4) and IS "
            "checked in at tools/osm-world/shards.json — the workflows read it from "
            "the checkout. If it is missing, regenerate it with cover.py (which also "
            "writes cover-geometries/) and commit both, or point --shards-json at a "
            "copy.",
            file=sys.stderr,
        )
        return 1

    data = json.loads(args.shards_json.read_text(encoding="utf-8"))
    if args.kind not in data:
        print(f"error: {args.shards_json} has no \"{args.kind}\" array", file=sys.stderr)
        return 1
    shards = data[args.kind]
    if not shards:
        print(f"error: {args.shards_json}[\"{args.kind}\"] is empty", file=sys.stderr)
        return 1

    batches = chunk(shards, args.batch_size)
    if len(batches) > args.max_jobs:
        print(
            f"error: {len(shards)} {args.kind} shards at batch-size {args.batch_size} "
            f"= {len(batches)} matrix jobs, over the --max-jobs cap of {args.max_jobs}. "
            "Raise --batch-size.",
            file=sys.stderr,
        )
        return 1

    prefix = args.id_prefix or args.kind
    matrix = [
        {
            "batch_id": f"{prefix}-{index:04d}",
            "shards": batch,
        }
        for index, batch in enumerate(batches)
    ]

    print(json.dumps(matrix, separators=(",", ":")))
    print(
        f"chunk-shards: {len(shards)} {args.kind} shards -> {len(matrix)} matrix jobs "
        f"(batch size {args.batch_size})",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
